# Generated by Django 4.2.7 on 2025-10-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancyservice',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for this consultancy service', null=True, upload_to='consultancy/covers/'),
        ),
    ]
