# Generated by Django 4.2.7 on 2025-10-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0002_consultancyservice_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructor', models.CharField(default='Moses Agbesi Katamani', max_length=100)),
                ('date', models.DateField(help_text='Masterclass date')),
                ('duration', models.CharField(help_text="e.g., '1 Day', '2 Days', '3 Hours'", max_length=50)),
                ('total_seats', models.PositiveIntegerField(default=30)),
                ('seats_available', models.PositiveIntegerField(default=30)),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image for this masterclass', null=True, upload_to='masterclasses/covers/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL', null=True)),
                ('is_upcoming', models.BooleanField(default=True, help_text='Mark as upcoming masterclass')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Masterclasses',
                'ordering': ['-date', 'title'],
            },
        ),
    ]
