# Generated by Django 4.2.7 on 2025-10-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0003_masterclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=50)),
                ('url', models.URLField(help_text='Full URL to your social media profile')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fab fa-facebook')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
