# Generated by Django 4.2.7 on 2025-10-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0004_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Kambel Consult', max_length=200)),
                ('hero_subtitle', models.TextField(default='Your trusted partner in career development and business excellence')),
                ('profile_name', models.CharField(default='Moses Agbesi Katamani', max_length=100)),
                ('profile_title', models.CharField(default='Chief Executive Officer', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, help_text='CEO Profile Picture', null=True, upload_to='hero/')),
                ('years_experience', models.CharField(default='15+', help_text="e.g., '15+' or '15 Years'", max_length=50)),
                ('years_label', models.CharField(default='Years Experience', help_text='Label for years', max_length=100)),
                ('years_description', models.CharField(default='Professional Development', max_length=100)),
                ('clients_count', models.CharField(default='5000+', help_text="e.g., '5000+' or '5000'", max_length=50)),
                ('clients_label', models.CharField(default='Clients', help_text='Label for clients', max_length=100)),
                ('clients_description', models.CharField(default='Successfully Helped', max_length=100)),
                ('publications_count', models.CharField(default='50+', help_text="e.g., '50+' or '50'", max_length=50)),
                ('publications_label', models.CharField(default='Publications', help_text='Label for publications', max_length=100)),
                ('publications_description', models.CharField(default='Authored Works', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Configuration',
                'verbose_name_plural': 'Hero Configuration',
            },
        ),
    ]
