# Generated by Django 4.2.7 on 2025-10-25 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0005_heroconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_years', models.CharField(default='15+', help_text="Years of experience (e.g., '15+')", max_length=50)),
                ('hero_clients', models.CharField(default='500+', help_text="Clients served (e.g., '500+')", max_length=50)),
                ('hero_publications', models.CharField(default='50+', help_text="Publications count (e.g., '50+')", max_length=50)),
                ('hero_speaking', models.CharField(default='100+', help_text="Speaking engagements (e.g., '100+')", max_length=50)),
                ('profile_name', models.CharField(default='Moses Agbesi Katamani', max_length=100)),
                ('profile_title', models.CharField(default='Founder & CEO, Kambel Consult', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture for about page', null=True, upload_to='about/')),
                ('bio_summary', models.TextField(default='A visionary leader and expert consultant with over 15 years of experience in education, career development, and business advisory services. Moses is dedicated to empowering individuals and organizations to achieve their full potential through strategic guidance and innovative solutions.')),
                ('tags', models.CharField(default='Education Expert,Career Coach,Business Advisor,Author,Speaker', help_text="Comma-separated tags (e.g., 'Education Expert,Career Coach')", max_length=500)),
                ('philosophy_quote', models.TextField(default='Education is the foundation of all progress. Through knowledge, guidance, and strategic thinking, we can unlock the potential within every individual and organization.')),
                ('cta_title', models.CharField(default='Ready to Work Together?', max_length=200)),
                ('cta_description', models.TextField(default="Let's discuss how I can help you achieve your goals and unlock your potential.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Configuration',
                'verbose_name_plural': 'About Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='SpeakingEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Topic or title of the speaking engagement', max_length=200)),
                ('event', models.CharField(help_text='Event or conference name', max_length=200)),
                ('date', models.CharField(help_text="e.g., 'March 2020' or '2020-03-15'", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Location of the event', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_engagements', to='kambel_admin.aboutconfig')),
            ],
            options={
                'verbose_name': 'Speaking Engagement',
                'verbose_name_plural': 'Speaking Engagements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalJourneyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('period', models.CharField(help_text="e.g., '2010-2015' or '2020 - Present'", max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='briefcase', help_text="Font Awesome icon name (without 'fa-' prefix)", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_items', to='kambel_admin.aboutconfig')),
            ],
            options={
                'verbose_name': 'Professional Journey Item',
                'verbose_name_plural': 'Professional Journey Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(help_text="e.g., 'Bachelor of Science in Business Administration'", max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.CharField(help_text="e.g., '2010' or '2010-2014'", max_length=50)),
                ('icon', models.CharField(default='graduation-cap', help_text='Font Awesome icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_items', to='kambel_admin.aboutconfig')),
            ],
            options={
                'verbose_name': 'Education & Qualification',
                'verbose_name_plural': 'Education & Qualifications',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.CharField(help_text="e.g., '2020' or '2020-2021'", max_length=50)),
                ('icon', models.CharField(default='trophy', help_text='Font Awesome icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='kambel_admin.aboutconfig')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
