# Generated by Django 4.2.7 on 2025-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0006_aboutconfig_speakingengagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='location',
            field=models.CharField(blank=True, help_text='City, State/Country', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(blank=True, help_text='Full street address'),
        ),
    ]
