# Generated by Django 4.2.7 on 2025-10-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0008_privacypolicy_termsconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main caption/title for the gallery item', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Short caption', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed description or additional information')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload image for image type', null=True, upload_to='gallery/images/')),
                ('video_url', models.URLField(blank=True, help_text='Video URL (YouTube, Vimeo, etc.) for video type')),
                ('video_file', models.FileField(blank=True, help_text='Or upload video file', null=True, upload_to='gallery/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Custom thumbnail (optional)', null=True, upload_to='gallery/thumbnails/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
