# Generated by Django 4.2.7 on 2025-10-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0009_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterclassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterclass_title', models.CharField(help_text='Masterclass title (if not linked to specific masterclass)', max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, help_text='Company/Organization', max_length=200)),
                ('experience_years', models.CharField(blank=True, help_text='Years of experience', max_length=20)),
                ('motivation', models.TextField(blank=True, help_text='Why interested in this masterclass')),
                ('subscribe_newsletter', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masterclass', models.ForeignKey(blank=True, help_text='Link to specific masterclass (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='kambel_admin.masterclass')),
            ],
            options={
                'verbose_name': 'Masterclass Registration',
                'verbose_name_plural': 'Masterclass Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
