# Generated by Django 4.2.7 on 2025-10-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0010_masterclassregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Registration price', max_digits=10),
        ),
    ]
