# Generated by Django 4.2.7 on 2025-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kambel_admin', '0011_masterclass_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Registration price (0.00 for free)', max_digits=10),
        ),
    ]
